import random


quotes = [
    "Some people can’t believe in themselves until someone else believes in them first. – Sean Maguire, Good Will Hunting",
    "It’s only after we’ve lost everything that we’re free to do anything. – Fight Club, Tyler Durden",
    "It is not our abilities that show what we truly are… it is our choices. – Dumbledore, Harry Potter and the Chamber of Secrets",
    "Why are you trying so hard to fit in when you were born to stand out? –  Movie What a girl wants",
    "Oh yes, the past can hurt. But you can either run from it, or learn from it. – Rafiki, from The Lion King",
    "If we didn’t do what we loved, we wouldn’t exist. – Adonis, Creed II",
    "At some point you’ve got to decide for yourself who you gonna be. Can’t let nobody make that decision for you. – Juan, Moonlight",
    "The best love is the kind that awakens the soul and makes us reach for more, that plants a fire in our hearts and brings peace to our minds. And that’s what you’ve given me. That’s what I’d hoped to give you forever. – Nicholas Sparks, The Notebook",
    "The greatest thing you’ll ever learn is just to love and be loved in return. – From Moulin Rouge",
    "Do, or do not. There is no try. – Yoda",
    "I’m scared of everything. I’m scared of what I saw. I’m scared of what I did, of who I am…. and most of all, I’m scared of walking out of this room and never feeling the rest of my whole life the way I feel when I’m with you. – Baby in Dirty Dancing",
    "Sometimes I wish I had never met you. Because then I could go to sleep at night not knowing there was someone like you out there. – Good Will Hunting",
    "Life moves pretty fast. If you don’t stop and look around once in a while, you could miss it. – Ferris, from Ferris Bueller’s Day Off",
    "Remember those posters that said, Today is the first day of the rest of your life? Well, that’s true of every day but one…the day you die. – American Beauty",
    "You’re nothing to me until you’re everything. – American Hustle",
    "Every man dies, not every man really lives. – Braveheart",
    "The truth is a matter of circumstances, it’s not all things to all people all the time. – Captain America: The Winter Soldier",
    "I believe whatever doesn’t kill you, simply makes you…stranger. – The Dark Knight, The Joker",
    "When you decide to be something, you can be it. – Frank Costello, The Departed",
    "Man is least himself when he talks in his own person. But if you give him a mask, he will tell you the truth. – The Fifth Estate, Julian Assange",
    "Ideals are peaceful. History is violent. – Don Collier, Fury",
    "When I despair, I remember that all through history the way of truth and love has always won. There have been tyrants and murderers, and for a time, they can seem invincible, but in the end, they always fall. Think of it, always. – Gandhi,  Gandhi (1982)",
    "All those moments will be lost in time… like tears in rain. – Rutger Hauer, Blade Runner",
    "A boy’s best friend is his mother. Anthony Perkins, Psycho",
    "Carpe diem. Seize the day, boys. Make your lives extraordinary. – Robin Williams, Dead Poets Society",
    "Get busy living, or get busy dying.  – Andy Dufresne, The Shawshank Redemption",
    "Hope. It is the only thing stronger than fear. A little hope is effective. A lot of hope is dangerous. A spark is fine, as long as it’s contained. – President Snow, The Hunger Games",
    "If you figure a way to live without serving a master, any master, then let the rest of us know, will you? For you’d be the first person in the history of the world. – Philip Seymour Hoffman, The Master",
    "Nobody’s perfect. – Some Like It Hot",
    "Now you’re looking for the secret, but you won’t find it, because of course you’re not really looking. You don’t really want to know. You want to be fooled. – The Prestige",
    "To call you stupid would be an insult to stupid people! – A Fish Called Wanda",
    "We all want to help one another. Human beings are like that. We want to live by each other’s happiness, not by each other’s misery. –  Charlie Chaplin, The Great Dictator ",
    "There’s no place like home.  The Wizard of Oz",
    "They may take our lives, but they will never take… our FREEDOM! – Braveheart",
    "Do, or do not. There is no try. – Yoda, Star Wars",
    "Love cannot be found where it doesn’t exist, nor can it be hidden where it truly does. – David Schwimmer, Kissing a Fool",
    "Don’t let anyone ever make you feel like you don’t deserve what you want. – Heath Ledger, 10 Things I Hate About You",
    "I don’t regret the things I’ve done, but those I did not do. – Empire Records",
    "My momma always said, Life is like a box of chocolates, you never know what you’re gonna get. – Forrest Gump",
    "Don’t ever let somebody tell you you can’t do something, not even me. Alright? You dream, you gotta protect it. People can’t do something themselves, they wanna tell you you can’t do it. If you want something, go get it. Period. – Chris Gardner, The Pursuit of Happyness",
    "To see the world, things dangerous to come to, to see behind walls, to draw closer, to find each other and to feel. That is the purpose of life. – The Secret Life of Walter Mitty",
    "All we have to decide is what to do with the time that is given to us. – Gandalf, Lord of the Rings: The Fellowship of the Ring",
    "Great men are not born great, they grow great. – Mario Puzo, The Godfather",
    "Just keep swimming. Just keep swimming. Just keep swimming, swimming, swimming. What do we do? We swim, swim. – Dory, Finding Nemo",
    "What we do in life echoes in eternity. – Maximus, Gladiator",
    "Every man dies, but not every man really lives. – William Wallace, Braveheart",
    "I know what I have to do now. I’ve got to keep breathing because tomorrow the sun will rise. Who knows what the tide could bring? – Cast Away",
    "Nobody is gonna hit as hard as life, but it ain’t how hard you can hit. It’s how hard you can get hit and keep moving forward. It’s how much you can take, and keep moving forward. That’s how winning is done. – Rocky, Rocky Balboa",
    "You drilled a hole in the dentist?! – Denise, Three Billboards Outside Ebbing, Missouri",
    "If you were not so stubborn you would make a great queen. I would make a great queen because I am stubborn…if that is what I wanted.—from an exchange between T’Challa and Nakia, Black Panther",
    "Being human is a condition which requires an anesthetic. – Freddie Mercury, Bohemian Rhapsody",
    "Dying for the right cause. It’s the most human thing we can do. — Freysa, Blade Runner 2049",
    "Fire. It is a reflection of our own mortality. – Dean Armitage, Get Out",
    "When will the lesson be learned! You cannot reason with a tiger when your head is in its mouth! – Winston Churchill, Darkest Hour",
    "We Shall Never Surrender. – Soldier, Dunkirk",
    "All the courage in the world cannot alter fact. — Niander Wallace, Blade Runner 2049",
    "How many times do I have to teach you: just because something works doesn’t mean it can’t be improved.—Shuri, Black Panther",
    "So if I’m not black enough and if I’m not white enough, then tell me, Tony, what am I!? – Don Shirley, Green Book",
    "Favor is a breeze that shifts direction all the time. – Harley, The Favourite",
    "That’s one small step for man, one giant leap for mankind. – Neil Armstrong, First Man",
    "Show me the money! – Jerry Maguire",
    "The only failure is not to try  – George Clooney",
    "Don’t be afraid to fail. It’s not the end of the world and in many ways it’s the first step toward learning something better and getting better at it –Jon Hamm",
    "After many years of self-flagellation, I’ve realized that beating myself up doesn’t get me anywhere  – Chris Pine",
    "Your regrets aren’t what you did, but what you didn’t do. So I take every opportunity  – Cameron Diaz",
    "I’ve come across many actors like me who didn’t have a backup. That drive & will made it work  – Clive Owen",
    "I say luck is when an opportunity comes along and you’re prepared for it  – Denzel Washington",
    "The best way to guarantee a loss is to quit  – Morgan Freeman",
    "I’m a big believer in ‘never say never’   – Jim Parsons",
    "Be so good they can’t ignore you - Steve Martin",
    "We’re going to be okay. You can rest now. – Pepper Potts, Avengers: Endgame",
    "Look, talent comes everywhere, but having something to say and a way to say it to have people listen to it, that’s a whole other bag. And unless you get out and you try to do it, you’ll never know. That’s just the truth. —Jackson Maine, A Star Is Born",
    "Hope is not a strategy. – Walker, Mission: Impossible – Fallout",
    "When you get a different vantage point it changes your perspective… It allows you to see things you should have seen a long time ago. – Neil Armstrong, First Man",
    "Who are we if we can’t protect them? We have to protect them. – Evelyn Abbott, A Quiet Place",
    "It’s not destroying. It’s making something new. – Lena, Annihilation",
    "I keep telling everybody they should move on and grow. Some do. But not us. – Steve Rogers, Avengers: Endgame",
    "You want to get out of the hole? First you’re going to have to put down the shovel. – Agent Rick Dicker, Incredibles 2",
    "Put two ships in the open sea without wind or ride and they will come together. – Arthur, Aquaman",
    "Good words. Good thoughts. Good deeds. – Bomi Bulsara, Bohemian Rhapsody",
    "We need people to care about the one life as much as you care about the millions. That way I don’t have to. – Sloan, Mission: Impossible – Fallout",
    "All you gotta do is trust me. —Jackson Maine, A Star Is Born",
    "Love is blind, Wade. – Blind Al, Deadpool",
    "When I drift off, I will dream about you. It’s always you. – Tony Stark, Avengers: Endgame",
    "Fortune favors the bold. – Jim Miami Beach, Bohemian Rhapsody",
    "I hope it’s okay if I love you forever, Jack. —Ally Maine, A Star Is Born",
    "We need to fail. We need to fail down here so we don’t fail up there.- Neil Armstrong, First Man",
    "Listen to me, it’s important that you learn these things. He just wants you to be able to take care of yourself, to take care of me, when I’m old, and grey, and I have no teeth. Don’t worry. – Evelyn Abbott, A Quiet Place",
    "It’s nice to be wanted. – Elastigirl, Incredibles 2",
    "Your mother always knew you were special. She believed… You would be the one to unite our two worlds. – Tom Curry, Aquaman",
    "I love your style. I think we should take more risks. – Mary Austin, Bohemian Rhapsody",
    "Terrorists are schoolboys hoping to spread propaganda through fear. Lane, Mission: Impossible – Fallout",
    "Even if there’s a small chance. We owe this, to everyone who’s not in this room, to try. – Natasha, Avengers: Endgame",
    "I didn’t think of you paying the price for a choice you never made. – Mr. Incredible, Incredibles 2",
    "Looks aren’t everything. – Blind Al, Deadpool",
    "We go to the moon not because it’s easy but because it’s hard. – President John F. Kennedy, First Man",
    "How do you balance the hard stuff with the life stuff? – Violet, Incredibles 2",
    "If I told you what happens, it won’t happen. – Stephen Strange, Avengers: Endgame",
    "I came because because I have no choice. I came to save my home and the people I love. – Tom Curry, Aquaman",
    "Everything is possible, even the impossible. – Mary Poppins, Mary Poppins Returns",
    "May the Force be with you. – Star Wars, 1977",
    "It’s not the years, honey. It’s the mileage.—Harrison Ford as Indiana Jones in Raiders of the Lost Ark",
    "I’m going to make him an offer he can’t refuse. – The Godfather, 1972",
    "It’s not who I am underneath but what I do that defines me.—Christian Bale as Batman in Batman Begins",
    "You can’t handle the truth! – A Few Good Men, 1992",
    "We’ll always have Paris.—Humphrey Bogart as Rick Blaine in Casablanca",
    "Every time a bell rings, an angel gets his wings. – It’s a Wonderful Life, 1946",
    "The greatest trick the Devil ever pulled was convincing the world he didn’t exist.—Kevin Spacey as Roger Verbal Kint in The Usual Suspects",
    "The Dude abides. – The Big Lebowski, 1998",
    "There’s no crying in baseball!—Tom Hanks as Jimmy Dugan in A League of Their Own",
    "Toto, I’ve a feeling we’re not in Kansas anymore. – The Wizard of Oz, 1939",
    "Only one thing counts in this life: Get them to sign on the line that is dotted.—Alec Baldwin as Blake in Glengarry Glen Ross",
    "This is the beginning of a beautiful friendship. – Casablanca, 1942",
    "Keep your friends close, but your enemies closer.—Al Pacino as Michael Corleone in The Godfather: Part II",
    "To infinity and beyond! – Toy Story, 1995",
    "Our lives are defined by opportunities even the ones we miss.—Brad Pitt as Benjamin Button in The Curious Case of Benjamin Button",
    "I am big! It’s the pictures that got small. – Sunset Boulevard, 1950",
    "Love means never having to say you’re sorry.—Ali MacGraw as Jennifer Cavilleri in Love Story",
    "I mean, funny like I’m a clown? I amuse you? – Goodfellas, 1990",
    "I’m not bad. I’m just drawn that way.—Kathleen Turner as Jessica Rabbit in Who Framed Roger Rabbit",
    "Don’t just fly, soar. – Dumbo (Dumbo)",
    "A wise man can learn more from his enemies than a fool from his friends. –Niki Lauda, Rush",
    "You control your destiny — you don’t need magic to do it. And there are no magical shortcuts to solving your problems. – Merida (Brave)",
    "Sometimes it is the people who no one imagines anything of who do the things that no one can imagine. – Alan Turing, The Imitation Game",
    "In every job that must be done, there is an element of fun. – Mary Poppins (Mary Poppins)",
    "Strange, isn’t it? Each man’s life touches so many other lives. When he isn’t around he leaves an awful hole, doesn’t he? – Clarence The Angel, It’s a Wonderful Life",
    "Your identity is your most valuable possession. Protect it. – Elastigirl (The Incredibles)",
    "The way it works is, you do the thing you’re scared shitless of, and you get the courage AFTER you do it, not before you do it. – Archie Gates, Three Kings",
    "Our fate lives within us. You only have to be brave enough to see it. – Merida (Brave)",
    "To find something, anything, a great truth or a lost pair of glasses, you must first believe there will be some advantage in finding it. – Jack Burden, All the King’s Men",
    "They may take our lives, but they’ll never take our freedom! – Braveheart",
    "So be prepared, be enthusiastic, and leave your bullshit attitude and baggage at the door because we don’t need it! – Wet Hot American Summer",
    "When you realize you want to spend the rest of your life with somebody, you want the rest of your life to start as soon as possible. – When Harry Met Sally",
    "You ain’t heard nothin’ yet! – The Jazz Singer",
    "You complete me. – Jerry Maguire",
    "I don’t want to survive. I want to live. – 12 Years a Slave",
    "You make me want to be a better man. – As Good as It Gets",
    "It’s alive! It’s alive! – Frankenstein",
    "Just when I thought I was out, they pull me back in. – The Godfather: Part III",
    "I have always depended on the kindness of strangers. – A Streetcar Named Desire",
    "By all means, move at a glacial pace. You know how that thrills me. — Miranda Priestly, The Devil Wears Prada",
    "Just a spoonful of sugar helps the medicine go down. — Mary Poppins",
    "From where I stand, the sun is shining all over the place. — Singin’ in the Rain",
    "No amount of money ever bought a second of time. – Tony Stark",
    "I’m the king of the world. — Titanic",
    "The hardest choices require the strongest wills. – Thanos",
    "Some people can never believe in themselves until someone believes in them. — Good Will Hunting",
    "Why do we fall, sir? So that we can learn to pick ourselves up. – Alfred Pennyworth",
    "After all, tomorrow is another day. — Gone with the Wind",
    "Those who never change their mind never change anything. – Winston Churchill",
    "Roads? Where we’re going we don’t need roads. – Back to the Future, 1985",
    ", ",
    "Nobody makes me bleed my own blood. Nobody! – Dodgeball: A True Underdog Story (2004)",
    "Fasten your seatbelts. It’s going to be a bumpy night. – All About Eve, 1950",
    "This is the day you will always remember as the day you almost caught Captain Jack Sparrow! – Pirates of the Caribbean: The Curse of the Black Pearl (2003)",
    "As my plastic surgeon always said, if you gotta go, go with a smile. —Jack Nicholson as The Joker in Batman",
    "I’m the guy who does his job. You must be the other guy. – The Departed (2006)",
    "By protecting others, you save yourselves. —Takashi Shimura as Kambei Shimada in Seven Samurai",
    "Look at me. I’m the captain now. – Captain Phillips (2013)",
    "The seaweed is always greener in somebody else’s lake. —Samuel E. Wright as Sebastian in The Little Mermaid",
    "With great power comes great responsibility. – Spider-Man (2002)",
    "You’re gonna need a bigger boat. – Jaws, 1975",
    "Calling it your job don’t make it right, boss. —Paul Newman as Luke in Cool Hand Luke",
    "If you build it, he will come. – Field of Dreams, 1989",
    "Try not. Do—or do not. There is no try. —Frank Oz as Yoda in Star Wars Episode V: The Empire Strikes Back",
    "The stuff that dreams are made of. – The Maltese Falcon, 1941",
    "You had me at ‘Hello.’ —Renee Zellweger as Dorothy Boyd in Jerry Maguire",
    "Today, I consider myself the luckiest man on the face of the earth. –The Pride of the Yankees, 1942",
    "Go ahead, make my day. – Sudden Impact, 1983",
    "Nobody puts Baby in a corner. – Dirty Dancing, 1987",
    "One morning I shot an elephant in my pajamas. How he got in my pajamas, I don’t know. – Animal Crackers, 1930",
    "Ogres are like onions. – Shrek (2001)",
    "In one of our designs even these mosquito bites will look like juicy, juicy mangoes! – Bend It Like Beckham (2002)",
    "You’re my boy, Blue! – Old School (2003)",
    "We could not talk or talk forever and still find things to not talk about. – Best in Show (2000)",
    "I just wanted to take another look at you. – A Star Is Born (2018)",
    "Hell is a teenage girl. – Jennifer’s Body (2009)",
    "Ye best start believin’ in ghost stories, Miss Turner. Yer in one. – Pirates of the Caribbean: The Curse of the Black Pearl (2003)",
    "For a guy with a four-digit IQ, I must have missed something. – Limitless (2011)",
    "Put some Windex on it. – My Big Fat Greek Wedding (2002)",
    "Do you know what happens to a toad when it’s struck by lightning? The same thing that happens to everything else. – X-Men (2000)",
    "I don’t have friends. I got family. – Furious 7 (2015)",
    "Didn’t I tell you not to come to my house? Nobody touches my child! – Obsessed (2009)",
    "You have bewitched me, body and soul. – Pride and Prejudice (2005)",
    "I have such doubts! – Doubt (2008)",
    "You gotta hear this one song. It’ll change your life, I swear. – Garden State (2004)",
    "To me, you are perfect. – Love Actually (2003)",
    "You’ve got red on you. – Shaun of the Dead (2004)",
    "My tastes are very singular. – Fifty Shades of Grey (2015)",
    "I want to play a game. – Saw (2004)",
    "In moonlight, black boys look blue. – Moonlight (2016)",
    "I wish I had done everything on earth with you - The Great Gatsby",
    "Some birds aren’t meant to be caged. Their feathers are just too bright.—Arnold Bennett, The Shawshank Redemption",
    "What I really want to do with my life — what I want to do for a living — is I want to be with your daughter. I’m good at it. - Say Anything",
    "You don’t know about real loss, because that only occurs when you love something more than you love yourself.—Sean Maguire, Good Will Hunting",
    "Life is not the amount of breaths you take, it’s the moments that take your breath away. - Hitch",
    "It’s only a passing thing, this shadow. Even darkness must pass. A new day will come. And when the sun shines it will shine out the clearer.—Samwise Gamgee, The Lord of the Rings: The Two Towers",
    "In my opinion, the best thing you can do is find someone who loves you for exactly what you are. Good mood, bad mood, ugly, pretty, handsome, what have you. - Juno",
    "You are what you love, not what loves you.—Donald Kaufman, Adaptation",
    "It would be a privilege to have my heart broken by you. - The Fault In Our Stars",
    "Don’t dream it, be it.—Dr. Frank-N-Furter, The Rocky Horror Picture Show",
    "I’ve come here with no expectations, only to profess, now that I am at liberty to do so, that my heart is, and always will be, yours. - Sense & Sensibility",
    "Happiness can be found even in the darkest of times. If one only remembers to turn on the light.—Albus Dumbledore, Harry Potter and the Prisoner of Azkaban",
    "Everything I have ever done, I’ve done for you. - Great Expectations",
    "A laugh can be a very powerful thing. Why, sometimes in life, it’s the only weapon we have.—Roger Rabbit, Who Framed Roger Rabbit?",
    "You’re the first boy I ever kissed, Jake, and I want you to be the last. - Sweet Home Alabama",
    "The past is just a story we tell ourselves.—Samantha, Her",
    "They say when you meet the love of your life, time stops, and that’s true. - Big Fish",
    "You mustn’t be afraid to dream a little bigger, darling.—Eames, Inception",
    "Here’s looking at you kid. - Casablanca",
    "Some infinities are simply bigger than other infinities. — Hazel Grace Lancaster, The Fault In Our Stars",
]

def random_quote():
    random_index = random.randint(0, len(quotes) - 1)
    return quotes[random_index]
